检查文件齐全
J7CAL/J7CAL pull request #1
Opened 2024-07-30 12:18 UTC by Hill23333

2024-07-30 12:33 UTC, allMagicNB requested changes

2024-07-30 12:33 UTC, allMagicNB commented on J7CAL/Modules/Helper.cmd
> +for /f "eol=C skip=1" %%i in ('certutil -hashfile %2% SHA1') do (
这边参数是不是写错了
```suggestion
for /f "eol=C skip=1" %%i in ('certutil -hashfile %~2 SHA1') do (
```

2024-07-30 12:33 UTC, allMagicNB commented on J7CAL/Modules/Helper.cmd
> +chcp 65001
```suggestion
```

模块内部别加，这是 Main.cmd 该做的事。

2024-07-30 12:33 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +for /f "delims=" %%i in ('echo %~2 ^| jq -j %3') do set "%~1=%%i"
这样只会 echo 文件名，你带 `--join` 可能得出问题，因为可能有些不止有一个过滤结果……

2024-07-30 12:58 UTC, allMagicNB requested changes
还得改改……

2024-07-30 12:58 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +:Json.GetValueFromFile <returnString> <jsonFile> <jsonPath>
```suggestion
:Json.GetValueFromFile <returnString> <jsonFile> <jsonFilter>
```

2024-07-30 12:58 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +@echo off
```suggestion
```

首先测试得看，其次 Main.cmd 已有。

2024-07-30 12:58 UTC, allMagicNB commented on J7CAL/Modules/VersionParser.cmd
> +set "version=%~2"
感觉这几行都没必要……？

2024-07-30 12:58 UTC, allMagicNB commented on J7CAL/Modules/VersionParser.cmd
> +call:Json.GetValueFromFile VersionParser.GetClientJarInfo.clientUrl VersionParser.GetClientJarInfo.clientJsonPath ".downloads.client.url"
能用 for 循环简化……

2024-07-31 08:59 UTC, allMagicNB requested changes
改延时变量

2024-07-31 08:59 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +for /f "delims=" %%i in ('echo %Json.GetValueFromFile.json% ^| jq %Json.GetValueFromFile.jsonFilter%') do set "Json.GetValueFromFile.return=%%i"
```suggestion
for /f "delims=" %%i in ('echo !Json.GetValueFromFile.json! ^| jq %Json.GetValueFromFile.jsonFilter%') do set "Json.GetValueFromFile.return=%%i"
```

2024-07-31 09:19 UTC, allMagicNB requested changes
改延时变量和变量名。

2024-07-31 09:19 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +for /f "delims=" %%i in ('echo !Json.GetValueFromFile.json! ^| jq %Json.GetValueFromFile.jsonFilter%') do set "Json.GetValueFromFile.return=%%i"
```suggestion
for /f "delims=" %%i in ('echo !Json.GetValueFromText.json! ^| jq %Json.GetValueFromText.jsonFilter%') do set "Json.GetValueFromText.return=%%i"
```

2024-07-31 09:50 UTC, Hill23333 commented on J7CAL/Modules/Json.cmd
> +for /f "delims=" %%i in ('echo !Json.GetValueFromFile.json! ^| jq %Json.GetValueFromFile.jsonFilter%') do set "Json.GetValueFromFile.return=%%i"
已修复

2024-07-31 10:09 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +for /f "delims=" %%i in ('echo !Json.GetValueFromFile.json! ^| jq %Json.GetValueFromFile.jsonFilter%') do set "Json.GetValueFromFile.return=%%i"
> 已修复

你修了没推上来。

2024-07-31 10:13 UTC, Hill23333 reviewed
经过测试VersionParser.GetClientJarInfo还是有问题，所以将解析json写进函数内部。GetValueFromText和GetValueFromFile在其他地方会用到。在这里直接嵌入json解析会更简洁

2024-07-31 15:04 UTC, allMagicNB requested changes

2024-07-31 15:04 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +call :Json.GetValueFromFile
```suggestion
call:Json.GetValueFromFile
```

2024-07-31 15:04 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +call :Json.GetValueFromText
```suggestion
call:Json.GetValueFromText
```

2024-07-31 15:04 UTC, allMagicNB commented on J7CAL/Modules/VersionParser.cmd
> +goto :EOF
我没看懂……

2024-07-31 15:04 UTC, allMagicNB commented on J7CAL/Modules/VersionParser.cmd
> +
```suggestion


```

程序集后空三行

2024-07-31 15:04 UTC, allMagicNB commented on J7CAL/Modules/Json.cmd
> +
```suggestion


```

程序集后空三行。

2024-07-31 15:04 UTC, allMagicNB commented on J7CAL/Modules/Helper.cmd
> +
```suggestion


```

程序集后空三行。

2024-07-31 15:04 UTC, allMagicNB commented on J7CAL/Modules/FileChecker.cmd
> +
这都没东西……
要不删了？

2024-07-31 15:04 UTC, allMagicNB commented on J7CAL/Main.cmd
```suggestion


```

再加一行。

2024-07-31 15:29 UTC, Hill23333 commented on J7CAL/Modules/VersionParser.cmd
> +goto :EOF
这里是把mcjson里面library的name转成path。
🌰：ca.weblite:java-objc-bridge:1.1
转换为： (省略)\.minecraft\libraries\ca\weblite\java-objc-bridge\1.1\java-objc-bridge-1.1.jar
因为某些版本的json不提供path因此需要将name转为path。

2024-08-01 13:00 UTC, Hill23333 commented on J7CAL/Modules/FileChecker.cmd
> +
彳亍口巴

2024-08-03 02:47 UTC, allMagicNB commented on J7CAL/Modules/VersionParser.cmd
> +goto :EOF
感觉可以简化……

2024-08-03 02:59 UTC, allMagicNB commented on J7CAL/Modules/VersionParser.cmd
> +goto :EOF
用 for 循环设定分隔符然后替换？

2024-08-03 03:06 UTC, allMagicNB requested changes
格式规定为：模块最后空三行，函数之间空两行。

2024-08-04 03:53 UTC, Hill23333 commented
我今天晚上就修复... 另外是否可以对curl访问添加UA头？
`J7CAL/启动器版本`
这对bmclapi的统计很有帮助。

2024-08-04 04:32 UTC, allMagicNB commented
> 我今天晚上就修复... 另外是否可以对curl访问添加UA头？
> `J7CAL/启动器版本`
> 这对bmclapi的统计很有帮助。
> 
> 

你赞助了吗
（204）

2024-08-04 05:54 UTC, Hill23333 commented
> > 我今天晚上就修复... 另外是否可以对curl访问添加UA头？
> > `J7CAL/启动器版本`
> > 这对bmclapi的统计很有帮助。
> 
> 你赞助了吗 （204）

赞助bmclapi？说实话没有...

2024-08-05 08:16 UTC, allMagicNB commented
~~草，才发现开源项目免费~~
[![image](https://github.com/user-attachments/assets/ca30501b-4173-4e87-a1b9-7c73e269b4b1)](https://afdian.com/@bangbang93)

2024-08-09 15:37 UTC, Hill23333 reviewed
现在GetClientLibrariesInfo的效率非常低，需要3秒才能获取所有lib的信息，而且有Bug（在非natives里除了name和isNatives全都是空） 希望指点...

2024-08-09 15:40 UTC, allMagicNB commented
等会我慢慢看吧……
~~还在写下载 Java~~

2024-08-09 15:56 UTC, Hill23333 commented
刚才研究出了提高效率的方法，尽可能减少调用jw并且将逻辑尽可能移到jq上（而不是batch） 希望有用吧（明天实装），但是bug我还是不知道为什么出现...

2024-08-09 15:57 UTC, Hill23333 commented
> 刚才研究出了提高效率的方法，尽可能减少调用jw并且将逻辑尽可能移到jq上（而不是batch） 希望有用吧（明天实装），但是bug我还是不知道为什么出现...

有错字(~jw~)

2024-08-10 13:50 UTC, Hill23333 commented
经过测试~还有GPT帮助~找到了直接获取参数的jq参数。速度非常快
`
 jq --arg arch 64 -r ".libraries[]|if.natives.windows?then(.natives.windows|gsub(\"\\$\\{arch\\}\";$arch))as$native|[(.name),(.downloads.classifiers[$native].sha1),(.downloads.classifiers[$native].size),(.downloads.classifiers[$native].url),true]|join(\",\")else[(.name),(.downloads.artifact.sha1),(.downloads.artifact.size),(.downloads.artifact.url),false]|join(\",\")end" 1.8.9.json 
`
![image](https://github.com/user-attachments/assets/cc4f3faf-8f38-48a5-9812-d3149559f779)
今天马上实装...

2024-08-10 16:09 UTC, Hill23333 reviewed
现在GetClientLibrariesInfo的速度是秒执行

2024-08-10 16:12 UTC, Hill23333 commented
下一步就是assets部分了...

2024-08-11 10:31 UTC, closed without merging